services:

  base-node-service:
    image: node:24
    working_dir: /app
    user: "node" #UID=1000
    env_file: .env
    volumes:
      - ./:/app

  lantranet:
    extends: base-node-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 10
    environment:
      - PORT=80
    ports:
      - 80:80
    command:
      - "bash"
      - "-c"
      - "npm i --verbose \
        && npx prisma migrate deploy \
        && npm run dev"

  prisma-studio:
    extends: base-node-service
    profiles: ["prisma-studio"]
    ports:
      - 5555:5555
    command: "npx prisma studio"

  # To run the playwright tests, run "docker compose run --rm playwright"
  playwright:
    image: mcr.microsoft.com/playwright:v1.57.0
    user: "ubuntu" #UID=1000
    depends_on:
      lantranet:
        condition: service_healthy
    working_dir: /app
    profiles: ["playwright"]
    environment:
      - DISPLAY=:0
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: "npx playwright"
    command: "test"
  
  playwright-report:
    extends: playwright
    ports:
      - 9323:9323
    command: "show-report --host=0.0.0.0 --port=9323"
